try{
    console.log(a)
} catch (err){
    console.log("A")
    console.log(err)
}

